### ISSUE TITLE
Runterladbare Zwischenspeicherungen

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sharepicgenerator#111]

**Comment by sbernhard** [comment]
... oder man speichert Zwischenspeicherungen pro Bild ab so dass man sie später wiederverwenden kann. Export / Import wäre natürlich auch schick.

**Comment by codeispoetry** [comment]
- [ ] Textlayout
- [ ] Zusatzbilder

**Comment by codeispoetry** [comment]
Zwischenspeicherungen können heruntergeladen werden.

**Comment by sbernhard** [comment]
Danke. Großartig!
