### ISSUE TITLE
Mastodon

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sharepicgenerator#124]
Feature Request: SharePic Größenverhältis für Mastodon ( hab spontan nur das hier gefunden: https://docs.joinmastodon.org/methods/statuses/media/ )

**Comment by codeispoetry** [comment]
es gibt keine empfohlenen bildamessungen

**Comment by b90g** [comment]
https://github.com/tootsuite/mastodon/pull/15690 - jetzt sinds 1920x1080

**Comment by codeispoetry** [comment]
done
