### ISSUE TITLE
[Feature Request] Create Table

### ISSUE THREAD

**Issue by prggz** [codeispoetry/sharepicgenerator#127]
Hi,

I have been asked by a colleague to help them create a table in the sharepic generator. (Voting results.)
It seems possible to me include this in the svg, however, only be using some hacking in the browser developer tools and I am not so firm in web development nowadays.

Do you think it is feasible to include this?

Thanks,

Zoey

**Comment by codeispoetry** [comment]
Dear Zoey,

thanks for you message. Could you send me an example pic with the table?

Thanks,
Tom

**Comment by prggz** [comment]
Dear Tom,

This is the "result":

https://www.facebook.com/photo/?fbid=10223755649862418&set=a.1527439869133

which - I think doesn't look optimal (font of the numbers) etc, but may help you understand the general idea.

Best,
Zoey

**Comment by codeispoetry** [comment]
Dear Zoey,

I've developed a markdown-editor, with which you can create tables (and lists) . These table can be uploaded. Here is the documentation: https://sharepicgenerator.de/documentation/markdown/

drop me a message, if this meets your request.

Yours,
Tom

**Comment by prggz** [comment]
Hi Tom,

Sorry, I'm this late in replying.

This certainly looks helpful and I will forward this to the person who asked :).

Obviously, it could be cool to have the markdown option within the sharepic generator... But I think, it should suffice as is. 

Should we close (and reopen if we ever felt this solution doesn't meet user's needs)?

Thanks again!

Zoey

**Comment by codeispoetry** [comment]
I'll have a look, how often this feature will be used.
/close
