### ISSUE TITLE
markdown image download broken?

### ISSUE THREAD

**Issue by sbernhard** [codeispoetry/sharepicgenerator#152]
Does the markdown image download still work? 
I guess, it should use base.php and use /assets location, too. 

Instead of using chromium, it would be nice to move to something smaller like https://www.npmjs.com/package/markdown-pdf (and then generate png form pdf)

**Comment by codeispoetry** [comment]
Det markdown editor geht wieder

**Comment by codeispoetry** [comment]
Kann dieses Ticket geschlossen werden?

**Comment by sbernhard** [comment]
sure!
