### ISSUE TITLE
Video: Hochladen und Verarbeiten eigenes Video schlägt fehl

### ISSUE THREAD

**Issue by sbernhard** [codeispoetry/sharepicgenerator#176]
.. da steht nur immer "Augenblick bitte. Deine Datei wird hochgeladen. 100 % hochgeladen" und nichts passiert

**Comment by sbernhard** [comment]
Idee was hier kaputt ist @codeispoetry ?

**Comment by codeispoetry** [comment]
danke für die Erinnerung. Da war ein Typo in einer Funktion. Ist in main bereinigt.
