### ISSUE TITLE
Video: Ausgabegröße und Bildeinstellungen komplett ausblenden

### ISSUE THREAD

**Issue by sbernhard** [codeispoetry/sharepicgenerator#177]
Aktuell werden nur die darunter liegenden Optionen von Ausgabegröße und Bildeinstellungen ausgeblendet. Schön wäre, dies komplett auszublenden und auch den User kenntlich machen, dass dies eben nicht unterstützt wird.

**Comment by codeispoetry** [comment]
Die Bildeinstellungen werden nun bei Videos versteckt.
