### ISSUE TITLE
Video Optionen "..." in Pixabay zeigen nichts an

### ISSUE THREAD

**Issue by sbernhard** [codeispoetry/sharepicgenerator#178]
Sucht man bei Pixabay nach Videos wird ein Player dargestellt. Darin sind auch "..." für "Optionen". Diese werden jedoch nicht angzeigt.

**Comment by codeispoetry** [comment]
Das scheint ein buggy Verhalten des Browsers zu sein. Ich habe die controls ganz ausgeschaltet und baue sie per Hand nach. Ist in main eingebaut.

**Comment by sbernhard** [comment]
Danke! Ein sync zwischen develop und main wird dann bald notwendig sein. :-)

**Comment by codeispoetry** [comment]
Ich will develop erst auf main mergen, wenn das mit der Galerie fertig ist

**Comment by sbernhard** [comment]
Was meinst du mit "das mit der Galerie"?

**Comment by codeispoetry** [comment]
![image](https://user-images.githubusercontent.com/6557858/94242725-c48a9000-ff16-11ea-8fb6-eb4d49d926e4.png)

Bei mir sieht es noch so aus:

**Comment by codeispoetry** [comment]
main und develop sind nun wieder auf dem gleichen Stand, nur mit dem Unterschied, dass bei main die Links zu Galerie und zur Mediengalerie versteckt sind

**Comment by sbernhard** [comment]
Geht die Mediengalerie oder die Sharepic-Galerie nicht?

**Comment by codeispoetry** [comment]
Die Mediengalerie möchte ich zunächst produktiv nicht nutzen. Das bedeutet für mich Supportaufwand, den ich derzeit nicht leisten kann. Die Galerie zeigt nicht immer das Sharepic und den Link zur Arbeitsdatei an.

**Comment by codeispoetry** [comment]
Ich habe in main und develop nun config-Variablen eingebaut, damit kann man einstellen, ob man die Mediengalerie und die Galerie einblenden möchte oder nicht.
