### ISSUE TITLE
 DSGVO: Recht auf Vergessenwerden

### ISSUE THREAD

**Issue by sbernhard** [codeispoetry/sharepicgenerator#196]
Das Logging und alle anderen Stellen auch, wo ggf. irgendwas von "Benutzern" oder eMails steht, da muss das Recht auf Vergessenwerden berücksichtigt werden - sprich nach einer Gewissen Zeit oder z.B. wenn der Benutzer gelöscht wird, dann muss der Eintrag anonymisiert oder komplett gelöscht werden.

**Comment by codeispoetry** [comment]
Gute Idee und danke für den Hinweis.
Aus den Log-Dateien werde ich den Usernamen pseudonymisieren. Meinst Du, es reicht, wenn ich da ein md5 draus mache?

Die einzelnen User-Verzeichnisse in persistent würde ich nur auf Anfrage löschen, oder? Genügt dazu ein Hinweis in der Datenschutzerklärung, dass man mir eine Mail schreibt mit der Bitte um Löschung?

**Comment by sbernhard** [comment]
Ein md5 aus dem Usernamen machen reicht. Ich würde sowas besser finden:
- Benutzername in den Log schreiben
- Log Daten sollte sowieso nicht ewig gehalten werden - spätestens nach 3 Monaten sollten die gelöscht werden
- Ein kleines Skript erstellen, welches im ganzen Projekt den Fall abdeckt, dass die Benutzerverzeichnisse, Logdateien, "andere Einträge wo Benutzername/eMail steht" entfernt wenn jemand "gelöscht" werden soll. 

Email in Datenschutzerklärung + HInweis dass man das Recht auf Vergessenewerden achtet sollte reichen.

**Comment by codeispoetry** [comment]
Ist mit  Commit 5af532be6f54bf39fad40b706461852c71c0c676 erledigt.
