### ISSUE TITLE
Hintergrundbild nur teilweise vergrünt

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#244]
habe ein Sharepic erstellt und das Hauptbild etwas eingegrünt; danach habe ich die Größe verändert (von Quadrat auf Querformat). Nun ist nur ein Teil des Bildes grün; und das lässt sich auch nicht mehr korrigieren.

**Comment by codeispoetry** [comment]
der Fehler müsste behoben sein
