### ISSUE TITLE
Schatten pro Text, statt pro Feld

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sharepicgenerator#248]

**Comment by Doogiemuc** [comment]
If i see it correctly, the the test is implemented as SVG.
It is possible to apply a drop shadow to SVG too. Here is an example.  It uses a SVG "filter":
http://dahlström.net/svg/filters/arrow-with-dropshadow.svg

**Comment by codeispoetry** [comment]
note to myself: 
```
text.svg.filterWith(function(add) {
  var blur = add.offset(0, 1).in(add.$sourceAlpha).gaussianBlur(1)

  add.blend(add.$source, blur)
})
```

**Comment by codeispoetry** [comment]
> If i see it correctly, the the test is implemented as SVG.
> It is possible to apply a drop shadow to SVG too. Here is an example. It uses a SVG "filter":
> [http://dahlström.net/svg/filters/arrow-with-dropshadow.svg](http://dahlstr%C3%B6m.net/svg/filters/arrow-with-dropshadow.svg)

vielen Dank

**Comment by codeispoetry** [comment]
ist umgesetzt
