### ISSUE TITLE
Vordergrundbilder: Size matching

### ISSUE THREAD

**Issue by b90g** [codeispoetry/sharepicgenerator#251]
sowohl in Firefox als auch in Chromium ist es mir nicht gelungen die bilder an die gleiche größe anzupassen.

Beide browser ohne Plugins

**Comment by b90g** [comment]
Bild 1 war n Png die anderen jpg, falls du beispielbilder brauchst sag bescheid

**Comment by codeispoetry** [comment]
Müsste jetzt gehen
