### ISSUE TITLE
Text verschwindet aus dem Bild

### ISSUE THREAD

**Issue by SaraNaNaNa** [codeispoetry/sharepicgenerator#254]
Schon von Anfang an, jetzt vermehrt, habe ich das Problem, dass der Text aus dem Textfeld wegspringt und nicht wieder kommt, insbesondere, aber nicht nur, wenn man es auf Zitate einstellt. 

Ich habe ein Macbook und nutze den Safari Browser. 

Tipps, wie ich das umgehen kann?

**Comment by codeispoetry** [comment]
Im Safari läuft der Sharepicgenerator leider nicht immer fehlerfrei. Kannst du stattdessen Chrome oder Firefox nutzen?
