### ISSUE TITLE
EH: Zweiter Nutzer kann kein Logo einbinden

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#260]
Der zweite Nutzer kann die meisten Menüpunkte nutzen, aber die Dropdown-Liste bei "Logo" enthält nur die Option "kein Logo".

**Comment by codeispoetry** [comment]
Kann er selbst ein Logo hochladen?

**Comment by jvoertzen2** [comment]
ja.

**Comment by codeispoetry** [comment]
Kann er das hochgeladene Logo einbinden?

**Comment by codeispoetry** [comment]
Ist das Ticket noch aktuell? Falls das Problem behoben ist, kannst Du das Ticket gerne schließen
