### ISSUE TITLE
EH: Hintergrundfarbe

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#261]
Als Hintergrundfarbe eines der EH-Blaus wäre super!

**Comment by codeispoetry** [comment]
Welcher Farbcode soll es denn sein?

**Comment by jvoertzen2** [comment]
84 / 136 / 199  (5488C7) bitte!

**Comment by codeispoetry** [comment]
Ich weiß nicht genau, was Du damit meinst.
Meinst Du im Bereich "Hauptbild" rechts oben die schwarze Fläche, wo man eine Hintergrundfarbe frei wählen kann?

Da kann ich z.B. Euer blau als Standardwert eintragen. Wäre das eine Lösung?
