### ISSUE TITLE
EH: Schrift standardmäßig links unten lassen

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#263]
Laut CD-Vorgabe hat der Hauptschrifttext eine bestimmte Entfernung vom linken und unteren Rand. So ist es auch eingestellt als Voreinstellung. Verändere ich aber den Schriftgrad, so verändert sich die Entfernung vom unteren Rand; bei großer Schrift ins Negative. Kannst Du das als Voreinstellung so machen, dass der Abstand nach links und unten gleich bleibt, und ich trotzdem noch mit der Maus den Ort des Textes ändern kann?

**Comment by codeispoetry** [comment]
ich habe folgende Lösung eingebaut: schieb den Text bitte mal nach links unten aus dem Bild raus. Der Text bounced dann zurück nach links unten. Passt das so?
