### ISSUE TITLE
EH Störer

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#264]
Wenn es möglich ist, hätte ich gerne den Störer als Kreis, aber so in eine der vier Ecken gesetzt, dass er angeschnitten ist. 
Die Farbe des Störers soll RGB 255/177/0 (ffb100) sein, die Schriftfarbe RGB 40 / 95 / 150 (285F96), die Schriftart Sauna Pro Reg. Danke!

![grafik](https://user-images.githubusercontent.com/78403072/122084884-8285df00-ce02-11eb-99ef-5e0de57e6af6.png)
![grafik](https://user-images.githubusercontent.com/78403072/122084923-89aced00-ce02-11eb-8441-fd2784cbad31.png)

**Comment by codeispoetry** [comment]
Du hast einen runden Störer, den kannst Du frei platzieren und die Hintergrundfarbe wählen. Passt das so? Dann kannst Du das Ticket gerne schließen.
