### ISSUE TITLE
EH Hintergrundbild ändert Format

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#265]
Das Hochladen eines Hintergrundbildes, das nicht der aktuellen Größe des Sharepics entspricht, verändert die Größe. Praktischer wars so wie ich es bei den Grünen in Erinnerung habe: Das Bild wird angeschnitten und kann verschoben werden.

**Comment by jvoertzen2** [comment]
Wenn ich anschließend die Größe des Bildes manuell zurückändere in ein quadratisches Layout, dann entsteht unten ein weißer Streifen. Ich glaube, das ist ein Streifen, auf den die Tönung des Bild nicht angewandt wird.

**Comment by jvoertzen2** [comment]
![grafik](https://user-images.githubusercontent.com/78403072/122086947-7e5ac100-ce04-11eb-84d0-52dc7c2323b5.png)

**Comment by codeispoetry** [comment]
Auch beim grünen Sharepicgenerator passt sich die Größe an das Bild an. Der weiße Streifen entseht, weil das Bild sonst wohl nicht ganz rein kann. 
In diesem Falle vergrößere bitte das Bild, dann müsste es passen
