### ISSUE TITLE
EH Hintergrundbild farbverfälscht

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#266]
Das Hochladen dieses Bildes:
![grafik](https://user-images.githubusercontent.com/78403072/122085825-66cf0880-ce03-11eb-81e8-e92e7d06540a.png)
führt zu diesem Ergebnis:
![grafik](https://user-images.githubusercontent.com/78403072/122085915-7a7a6f00-ce03-11eb-935d-1ec424a3fac3.png)
Einstellung für Tönung ist "unverändert".
Möglicherweise hat sich hier ein Grün von den Grünen eingeschlichen?
Der Effekt ist reproduzierbar mit diesem Bild, tritt aber nicht auf, wenn ich ein Bild von Pixabay direkt nehme.
Der Effekt tritt nicht auf, wenn ich das Bild zunächst in ein JPG umwandle. Aber dann hat es halt leider keine transparente Farbe mehr.

**Comment by codeispoetry** [comment]
Das ist kein Bug, sondern ein Feature. :)
Gilt nur für die Bundestagswahl. Ich habe das für Euch eben ausgeschatet.
