### ISSUE TITLE
Claim reparieren

### ISSUE THREAD

**Issue by codeispoetry** [codeispoetry/sharepicgenerator#268]
Bzgl. Claim: der sieht für mich noch nicht ganz richtig aus. Hast du 
Zugriff auf die Wolke?
Dort liegen die Claim-Dateien ab auch als .SVG. Magst du die einfach da 
einbetten?

**Comment by codeispoetry** [comment]
Ich baue den Claim im Sharepicgenerator nach. Dann wird er schneller geladen und sauberer gerendert. Außerdem kann er dann ggf. doch mal geändert werden. Passt das jetzt so, wie ich ihn eingebaut habe?

**Comment by vonmiristdasnicht** [comment]
Ehrlich gesagt sieht er noch nicht so gut aus. Vor allem der Abstand nach rechts raus zur Kante. Die Agentur hat da ewig dran geschliffen, wie der genau aussehen soll. Wäre es doch irgendwie möglich dort den svg-Code der vektorgrafik reinzusetzen? Wenn ich das richtig sehe, wird das von dir nachgebaute ja auch als svg gerendert.

**Comment by codeispoetry** [comment]
Okay, dann baue ich das ein

**Comment by codeispoetry** [comment]
Jetzt wird der bereitgestellte Claim geladen und nicht mehr nachgezeichnet.
