### ISSUE TITLE
EH: Suche mit 2 Wörtern funktioniert nicht

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#273]
Die Suche nach einem Hintergrundbild nach "Katze Baum" ergab bei pixabay keine Treffer (bei pixabay direkt sind es 18 Seiten).

**Comment by codeispoetry** [comment]
Jetzt ist die Suchsprache auf Deutsch eingestellt, damit funktionieren auch mehrere Begriffe
