### ISSUE TITLE
Moving around or entering Claim is funky

### ISSUE THREAD

**Issue by stuffmc** [codeispoetry/sharepicgenerator#283]
https://user-images.githubusercontent.com/66973/125437003-f1298535-d8d0-4113-b2b5-3e187748ca12.mov

Sorry for the German and the "Poof Poof", that's what we say in French.

Not better than "Zoob Zoob" which we also say and makes arabic speakers go 🤣

**Comment by codeispoetry** [comment]
The code has been refactored. So the problem might not exist any longer.
