### ISSUE TITLE
Transparent JPEG? :-)

### ISSUE THREAD

**Issue by stuffmc** [codeispoetry/sharepicgenerator#284]
The file `addpic1.jpg` is probably a PNG, right?

[sharepic_manu.zip](https://github.com/codeispoetry/sharepicgenerator/files/6808236/sharepic_manu.zip)

Also this ZIP doesn't resolve yet when loading.

**Comment by codeispoetry** [comment]
Dankeschön. Arbeitsdateien sind nun generell nicht mehr möglich. Damit gab es zu viele Probleme.

**Comment by stuffmc** [comment]
Sehr sehr sehr sehr sehr sehr schade :(
