### ISSUE TITLE
Idee: Vordergrundbild mit Text

### ISSUE THREAD

**Issue by florianbieser** [codeispoetry/sharepicgenerator#290]
Ich würde gerne für Veranstaltungen die Bilder der Teilnehmenden mittels Vordergrundbildern einbinden und mit dem Namen der jeweiligen Person beschriften. Kann man den Vordergrundbildern noch ein optionales Textfeld mitgeben?

**Comment by codeispoetry** [comment]
danke für die Idee. Das geht jetzt :)
