### ISSUE TITLE
EH: Text verschwindet bei Schatten

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#298]
Beim Anklicken von "Schatten" verschwindet der Text (hinter dem Bild?). Er erscheint wieder, wenn ich den Schatten ausblende. Es hat nichts geändert, die Schaltfläche "Text in den Vordergrund" zu verwenden.

Ablauf:

- eigenes Bild hochgeladen
- Text eingegeben
- Text mehrfach bearbeitet, auch nach außerhalb des Bildes gerückt, um ihn wieder links unten zu platzieren; alles hat funktioniert
- Schatten angeklickt --> Text verschwindet.

anbei die Arbeitsdatei 
[polarisierung-entsteht-durch-v.zip](https://github.com/codeispoetry/sharepicgenerator/files/7751281/polarisierung-entsteht-durch-v.zip)

**Comment by codeispoetry** [comment]
Dankeschön für den Bugreport. Ich konnte den Fehler im Firefox nachstellen. Im Chrome tritt er bei mir nicht auf.
Das scheint ein Bug im Browser zu sein.
Wenn der Text weg ist, trage bitte ein Leerzeichen oder anderes Zeichen bei Störertext ein. Das kannst du auch gleich wieder löschen. Dann ist der Text wieder da. 

Lass uns dieses unerwartete Verhalten weiterhin beobachten, evtl. ist es mit dem nächsten Firefox-Update hinfällig.
