### ISSUE TITLE
EH: Störer lässt sich nicht mehr platzieren

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#299]
[nachdenken-ueber-corona-ohne-i.zip](https://github.com/codeispoetry/sharepicgenerator/files/7775760/nachdenken-ueber-corona-ohne-i.zip)

Der Störer lässt sich überraschend nciht mehr verschieben - bis eben gings noch. Letzte Änderung war, dass ich die Größer vergrößert habe.
Workaround: Größe erneut  verändert. Der Störer lässt sich jetzt in einem kleinen Bereich in seinem linken Bereich anfassen und bewegen.

**Comment by codeispoetry** [comment]
Ich kann den Fehler bei mir leider nicht nachstellen. In welchem Browser muss ich was genau machen, damit der Fehler auftritt?
