### ISSUE TITLE
Hochgeladenes Bild wird in Schleife immer nur in einem Layout gezeigt

### ISSUE THREAD

**Issue by ChristophOberst** [codeispoetry/sharepicgenerator#301]
Hochgeladenes Bild wird in Schleife immer nur in einem Layout gezeigt, nach dem Wechsel des Layouts (Bundeslayout) springt es immer auf das basis eingestellte Layout zurück.

**Comment by codeispoetry** [comment]
Hallo, 

was meinst Du mit "in Schleife in einem Layout"? Kannst Du hier vielleicht einen Screenshot posten bitte?

**Comment by ChristophOberst** [comment]
Danke für die Antwort: Das habe ich schlecht erklärt. 
Also wenn ich das Layout umstelle nachdem ich ein Foto hochgeladen habe, ist das Foto weg und es fängt bei Null an. Das war früher besser.  Zudem vermisse ich ein Bundeslayout ohne die "Bereit, weil ihr es seid Banderole" oder eine Abwahlmöglichkeit. Eben ist mir etwas weiteres aufgefallen, im alten Layout beim Textzeilen verschieben auf dem Bild verschwindet der Text (ausserhalb des Rahmens?)

**Comment by codeispoetry** [comment]
Hallo,

wenn Du bei "Text" auf "Layout schwebend" gehtst, verschwindet das Bild, verstehe ich Dich richtig? Welchen Browser verwendest Du? Könntest Du zwei Screenshots posten, vorher und nach dem Verschwinden? Bei mir kann ich den Fehler nämlich leider noch nicht nachstellen, da funktioniert es wie gewollt.

**Comment by ChristophOberst** [comment]
Das Problem mit dem verschwindendem Text, der bei verschieben der Position des Textes per dragndrop passierte besteht nicht mehr. 
Wenn ich nach upload eines Bildes und Eingabe von Text im alten Layout, siehe hier: 
![test2](https://user-images.githubusercontent.com/98588550/151810495-db86df7a-6d0f-4eb8-a309-eb379fb2c902.png)
doch noch das Layout wechseln möchte, beginnt die Eingabe bei Null (Text und Bild sind weg). Das war vor dem update angenehmer, nämlich einfach zwischen den Layouts umschaltbar (Bild blieb hochgeladen und Text wechselte in anderes Layout)
Ich nutze Windows und Chrome für den Generator.
