### ISSUE TITLE
Idee: Buttons (zum Anstecken)

### ISSUE THREAD

**Issue by Zauba** [codeispoetry/sharepicgenerator#315]
Kann man eine Vorlage einfügen, mit der man mit dem sharepic Generator Buttons erstellen kann? 

Größen: 59mm, 50mm, 38mm, 32mm

die Größen findet man zum Beispiel hier:
https://www.badgematic.de/pub/media/pdf/Druckvorlagen-59-mm-Buttons.pdf
https://www.badgematic.de/pub/media/pdf/Druckvorlagen-50-mm-Buttons.pdf
https://www.badgematic.de/pub/media/pdf/Druckvorlagen-38-mm-Buttons.pdf
https://www.badgematic.de/pub/media/pdf/Druckvorlagen-32-mm-Buttons.pdf

**Comment by codeispoetry** [comment]
Danke für die Idee. Du kannst die Größe eines Sharepics selbst einstellen
