### ISSUE TITLE
EH: Bug: Text verrutscht

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#331]
Text verrutscht, wenn ich die Farbe wechsle
Idealerweise implementieren wie zuvor, dass Text automatisch links unten platziert wird mit angemessenem Rand

**Comment by codeispoetry** [comment]
BItte lade doch mal mit Shift-Reload die Seite neu. Ich kann den Fehler nicht nachstellen

**Comment by jvoertzen2** [comment]
Bug persistiert, auch in develop-Version.

**Comment by jvoertzen2** [comment]
Text verrutscht auch, wenn ich nur Buchstaben ergänze.

**Comment by codeispoetry** [comment]
Ich kann den Fehler leider immer noch nicht nachstellen. Welchen Browser benutzt du?

**Comment by jvoertzen2** [comment]
Firefox, neueste Version, unter Windows, neueste Version.

**Comment by codeispoetry** [comment]
Der Fehler ist behoben
