### ISSUE TITLE
EH: Bug: Schriftart

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#332]
Eigene Schriftart fehlt im WYSIWYG (für alle Texte) – aber erscheint dann im JPG, was natürlich die Optik verzerrt.

**Comment by codeispoetry** [comment]
Hast Du einen Screenshot für mich? Ich kann den Fehler nicht reproduzieren.

**Comment by jvoertzen2** [comment]
Fehler bei mir! Ich habe das "develop" in der Adresse vergessen.
