### ISSUE TITLE
EH: CR: Schatten bei Schrift einführen

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#333]
Option für Schatten gibt es nicht mehr, ist aber bei meinen bunten Bildern wichtig

**Comment by codeispoetry** [comment]
Hast du den wirklich nicht? Unter develop sehe ich ihn

**Comment by codeispoetry** [comment]
Falls Du den Schatten nun doch hast, kannst Du dieses Ticket gerne schließen
