### ISSUE TITLE
EH Bug: Logo Hochladen

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#335]
Das schon hinterlegte Logo ist im Generator sichtbar, aber im heruntergeladenen JPG hat es Bildfehler (vertikale Streifen)

Beim Hochladen eines weiteren Logo verschwindet das vorherige, das neue taucht nicht auf, und es gibt auch keine Auswahl von mehreren Logos (die es bisher gab). Das neu hochgelandene Logo ist dann im heruntergelandenen JPG doch vorhanden.

**Comment by jvoertzen2** [comment]
Dieser Bug ist jetzt nur noch ein Change Request, denn:
- Bildfehler tritt nicht auf unter "develop".
- Beim Hochladen ist das neue Logo sichtbar unter "develop", das alte verschwindert, und so sieht es auch im heruntergeladenen auf.
- Aber: Mehrere Logos zur Auswahl gibt es nicht mehr, und das war sehr nützlich für verschiedene Farben. Ist aber kein Prio1-Request.

**Comment by codeispoetry** [comment]
Ich kann den Bug leider nicht nachstellen. Tritt der Fehler noch bei Dir auf?
Zurzeit kann man nur ein Logo hochladen. Wenn man ein neues hochlädt, wird das bisherige überschrieben.

**Comment by codeispoetry** [comment]
Dann schließe ich das Ticket hier einstweilen. Mehrere Logos wird es in naher Zukunft wohl leider nicht geben.
