### ISSUE TITLE
EH CR: blau getöntes Bild

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#336]
Die frühere Version, Bilder in der Hauptfarbe des CD einfärben zu können, haben wir viel genutzt.
Statt also die Sättigung Richtung s/w senken zu können wie jetzt, wäre es schön, wenn man Bilder schrittweise Richtung Blau (5488C7) färben könnte.

**Comment by codeispoetry** [comment]
Man kann jetzt das Bild auch blau einfärben.
