### ISSUE TITLE
EH Bug: Auflösung Hintergrundbild

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#337]
Beim Hochladen eines hochaufgelösten Bildes 600x600 als Hintergrundbild wird es verpixelt - ich meine zu sehen, dass sich die Farbauflösung verringert, aber es könnten auch die Pixel sein. Der Fehler bleibt auch beim Herunterladen des Sharepics bestehen.

Original: 
![Hintergrund_dunkel_01](https://user-images.githubusercontent.com/78403072/227453802-a6864e28-8b17-4504-a37f-e2dbc977babd.jpg)

im Generator: 
![grafik](https://user-images.githubusercontent.com/78403072/227453398-2a805f02-9fdf-40d0-94a6-3f2fe6eeeebb.png)

**Comment by codeispoetry** [comment]
Danke für den Hinweis. Der Fehler ist behoben.
