### ISSUE TITLE
EH: CR: Störer in den Vordergrund

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#338]
Es wäre gut, wenn man den Störer vor die Vordergrundbilder schalten könnte; also: für den Störer auch eine Option "in den Vordergrund bringen", wie es sie bei den Vordergrundbildern gibt.

**Comment by jvoertzen2** [comment]
Ah, workaround: Schriftartfarbe des Störers ändern --> rutscht in den Vordergrund.

**Comment by codeispoetry** [comment]
Da gibt es jetzt einen Button, um den Störer in den Vordergrund zu holen.
