### ISSUE TITLE
EH: Bug: Logo "weint"

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#339]
Das Logo "weint": die unterste Zeile wird zwar nicht im Generator, aber im heruntergeladenen Bild, nach unten weitergezogen. Dieser Fehler tritt auch mit anderen Logos auf.

![wer-bestimmt-d-allgemein-quadratisch](https://user-images.githubusercontent.com/78403072/228178437-9cd930e9-4c96-4b9e-8cb2-f92b4b1a23c1.png)

**Comment by codeispoetry** [comment]
Danke für die Fehlermeldung. Der Bug ist behoben.
