### ISSUE TITLE
CR: Schatten hinter Text

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#340]
Die Nutzbarkeit des SPG würde enorm steigen, wenn es wieder Schatten hinter den Texten gäbe, wie es in Vorgängerversionen der Fall war. Ohne die Schatten sind farbige Bilder schwer nutzbar, weil der Text immer hier oder da schwer lesbar wird.

**Comment by codeispoetry** [comment]
Über dem Text findest du ein Menü. Im Menüpunkt "Bearbeiten" gibt es den Punkt "Schatten unter Text".
