### ISSUE TITLE
SQL Schema

### ISSUE THREAD

**Issue by manuelportela** [codeispoetry/sharepicgenerator#346]
Where can i find the SQL Schema for the user and log DB?

**Comment by codeispoetry** [comment]
Please finde the schemata here:
https://github.com/codeispoetry/sharepicgenerator/blob/0073ca0d432dd9959f2b639b6fb544d49edb0d50/code/dist/lib/log_functions.php#L6

https://github.com/codeispoetry/sharepicgenerator/blob/0073ca0d432dd9959f2b639b6fb544d49edb0d50/code/dist/lib/user_functions.php#L366
