### ISSUE TITLE
merkwürdiges Submenü

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#350]
Sowohl, wenn ich mit dem Logo hantiere, als jetzt auch beim "Urheberrechtshinweis" erscheint ein Submenü, das so nicht gemeint sein kann:
![grafik](https://github.com/codeispoetry/sharepicgenerator/assets/78403072/35bf91e1-efd6-4b61-a4ca-4da119eabdc8)

...und merkwürdige Effekte erzielt, z.B. mehrfacher Klick auf "U" (underline) führt dazu, dass sich der Copyrighthinweis dreht und das Feld größer wird, aber leer bleibt.

Beim Rumspielen damit verschwinder der Copyright-Hinweis auf einmal ganz, als ich das Logo anfasse, und ich kann ihn auch nicht wieder herstellen.

**Comment by jvoertzen2** [comment]
parallel erscheint ein Hinweis auf einen Fehler - vielleicht sind meine Bugreports also überflüssig?
![grafik](https://github.com/codeispoetry/sharepicgenerator/assets/78403072/a94336e0-160c-4ba4-a4ae-4a1e95d1c873)

**Comment by codeispoetry** [comment]
siehe #349, deshalb #close
