### ISSUE TITLE
CR: Störer

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#351]
Hintergrundfarbe gelb-orange wäre gut. 
![grafik](https://github.com/codeispoetry/sharepicgenerator/assets/78403072/071952cd-c749-439d-a1b7-2cbc7f621f58)

Schriftart Sauna pro reg wäre gut.

Rand einstellen können wäre gut.

**Comment by codeispoetry** [comment]
Die Farbe kann Du ja selsbt einstellen. Die Schriftart ist ja schon drin
