### ISSUE TITLE
Menüpunkt "Zwischenspeichern" ist gefährlich

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#352]
Wenn ich auf den Namen einer zwischengespeicherten Datei klicke, geht das aktuelle Sharepic verloren. Da wäre eine Warnung nützlich, oder eine Bezeichnung "lade Sharepic" oder so.

**Comment by codeispoetry** [comment]
hab einen zwischenschritt eingebaut
