### ISSUE TITLE
CR: Schriftgröße

### ISSUE THREAD

**Issue by jvoertzen2** [codeispoetry/sharepicgenerator#353]
für Sharepics finde ich Schriftgrößen unter 16 eher entbehrlich, aber es wäre schön, darüber noch Varianz zu haben, z.B. noch die Schriftgrößen 30 und 42. Beim alten Modell ging das ja stufenlos, aber dafür habe ich bei Textfeld keine Option gefunden.

**Comment by codeispoetry** [comment]
jetzt kann man stufenlos einstellen
